server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    threads:
      max: 249
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zyy1103..
    url: "jdbc:mysql://127.0.0.1:3306/bank?ServerTimezone=UTC&usingSsl=false"
  mvc:
    view:
      suffix: .html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

rocketmq:
  producer:
    group: springBootGroup
  name-server: localhost:9876
  server:
    port: 1100

redis:
  port: 6379
  addr: 121.43.41.221
  pass: wangwangduifendui